version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django_app
    ports:
      - "8001:8000" # Expose Django's development server on port 8001
    volumes:
      - .:/app # Mount the local project directory inside the container
    env_file:
      - ./MedAppBackend/.env # Load environment variables from the .env file
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
