version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django_app
    ports:
      - "8001:8000"
    volumes:
      - .:/app
    env_file:
      # - .env
    command: >
      sh -c "python manage.py migrate &&
             gunicorn -b 0.0.0.0:8000 MedAppBackend.wsgi:application"

volumes:
  db_data:
