# Generated by Django 5.1.2 on 2024-11-03 21:55

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedAppApi', '0003_basicpatient_propatient_patient_appointments_booked_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=60.0, max_digits=10),
        ),
        migrations.CreateModel(
            name='SatisfactionRatings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MedAppApi.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MedAppApi.patient')),
            ],
        ),
    ]
