# Generated by Django 5.1.3 on 2024-11-06 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MedAppApi", "0005_rename_satisfactionratings_ratings"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="basicpatient",
            name="patient_ptr",
        ),
        migrations.RemoveField(
            model_name="propatient",
            name="patient_ptr",
        ),
        migrations.RemoveField(
            model_name="ratings",
            name="doctor",
        ),
        migrations.RemoveField(
            model_name="ratings",
            name="patient",
        ),
        migrations.RemoveField(
            model_name="testimonials",
            name="user",
        ),
        migrations.DeleteModel(
            name="TestUser",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="appointments_booked",
        ),
        migrations.AddField(
            model_name="doctor",
            name="short_bio",
            field=models.CharField(default="Experienced professional", max_length=150),
        ),
        migrations.AddField(
            model_name="patient",
            name="date_of_birth",
            field=models.DateField(default="2000-01-01"),
        ),
        migrations.DeleteModel(
            name="BasicPatient",
        ),
        migrations.DeleteModel(
            name="ProPatient",
        ),
        migrations.DeleteModel(
            name="Ratings",
        ),
        migrations.DeleteModel(
            name="Testimonials",
        ),
    ]
