# Generated by Django 5.1.3 on 2024-11-08 00:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MedAppApi", "0007_alter_patient_date_of_birth_userprofile_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="appointment",
            old_name="symptom_summary",
            new_name="symptoms",
        ),
        migrations.RemoveField(
            model_name="appointment",
            name="booking_date",
        ),
        migrations.RemoveField(
            model_name="appointment",
            name="cost",
        ),
        migrations.AddField(
            model_name="appointment",
            name="ai_summarized_symptoms",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="appointment",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="appointment",
            name="date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="appointment",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="appointment",
            name="time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="appointment",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="doctor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="appointments",
                to="MedAppApi.doctor",
            ),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="appointments",
                to="MedAppApi.patient",
            ),
        ),
    ]
