# Generated by Django 5.1.3 on 2024-11-11 19:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedAppApi', '0008_rename_symptom_summary_appointment_symptoms_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 11, 11, 19, 2, 42, 983429, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 11, 11, 19, 3, 2, 359526, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appointment',
            name='time',
            field=models.TimeField(default=datetime.datetime(2024, 11, 11, 19, 3, 11, 927503, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
